#![recursion_limit = "256"]

use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

use ophiolite::{
    GatherAxisKind, GatherInteractionChanged, GatherProbe, GatherProbeChanged, GatherSampleDomain,
    GatherView, GatherViewport, GatherViewportChanged, ResolvedWellPanelSourceDto,
    ResolvedWellPanelWellDto, WELL_PANEL_CONTRACT_VERSION, WellPanelDepthSampleDto,
    WellPanelDrillingObservationDto, WellPanelDrillingSetDto, WellPanelLogCurveDto,
    WellPanelPressureObservationDto, WellPanelPressureSetDto, WellPanelRequestDto,
    WellPanelTopRowDto, WellPanelTopSetDto, WellPanelTrajectoryDto, WellPanelTrajectoryRowDto,
};
use schemars::schema_for;
use ts_rs::TS;

fn main() -> Result<(), Box<dyn Error>> {
    let repo_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("scripts/contracts-export should live two levels under repo root")
        .to_path_buf();

    let package_root = repo_root
        .join("contracts")
        .join("ts")
        .join("ophiolite-contracts");
    let generated_dir = package_root.join("src").join("generated");
    let schema_dir = package_root.join("schemas");

    fs::create_dir_all(&generated_dir)?;
    fs::create_dir_all(&schema_dir)?;

    export_ts_types(&generated_dir)?;
    write_generated_index(&generated_dir)?;
    write_schema_bundle(&schema_dir)?;

    Ok(())
}

fn export_ts_types(output_dir: &Path) -> Result<(), Box<dyn Error>> {
    for file in [
        "ResolvedWellPanelSourceDto.ts",
        "ResolvedWellPanelWellDto.ts",
        "GatherAxisKind.ts",
        "GatherInteractionChanged.ts",
        "GatherProbe.ts",
        "GatherProbeChanged.ts",
        "GatherSampleDomain.ts",
        "GatherView.ts",
        "GatherViewport.ts",
        "GatherViewportChanged.ts",
        "WellPanelDepthSampleDto.ts",
        "WellPanelDrillingObservationDto.ts",
        "WellPanelDrillingSetDto.ts",
        "WellPanelLogCurveDto.ts",
        "WellPanelPressureObservationDto.ts",
        "WellPanelPressureSetDto.ts",
        "WellPanelRequestDto.ts",
        "WellPanelTopRowDto.ts",
        "WellPanelTopSetDto.ts",
        "WellPanelTrajectoryDto.ts",
        "WellPanelTrajectoryRowDto.ts",
        "well-panel-contract-version.ts",
        "index.ts",
    ] {
        let path = output_dir.join(file);
        if path.exists() {
            fs::remove_file(path)?;
        }
    }

    WellPanelRequestDto::export_all_to(output_dir)?;
    ResolvedWellPanelSourceDto::export_all_to(output_dir)?;
    GatherView::export_all_to(output_dir)?;
    GatherViewportChanged::export_all_to(output_dir)?;
    GatherProbeChanged::export_all_to(output_dir)?;
    GatherInteractionChanged::export_all_to(output_dir)?;

    fs::write(
        output_dir.join("well-panel-contract-version.ts"),
        format!(
            "// Generated by `cargo run -p contracts-export`\nexport const WELL_PANEL_CONTRACT_VERSION = {WELL_PANEL_CONTRACT_VERSION} as const;\n"
        ),
    )?;

    Ok(())
}

fn write_generated_index(output_dir: &Path) -> Result<(), Box<dyn Error>> {
    let index = r#"// Generated by `cargo run -p contracts-export`
export type { ResolvedWellPanelSourceDto } from "./ResolvedWellPanelSourceDto";
export type { ResolvedWellPanelWellDto } from "./ResolvedWellPanelWellDto";
export type { GatherAxisKind } from "./GatherAxisKind";
export type { GatherInteractionChanged } from "./GatherInteractionChanged";
export type { GatherProbe } from "./GatherProbe";
export type { GatherProbeChanged } from "./GatherProbeChanged";
export type { GatherSampleDomain } from "./GatherSampleDomain";
export type { GatherView } from "./GatherView";
export type { GatherViewport } from "./GatherViewport";
export type { GatherViewportChanged } from "./GatherViewportChanged";
export type { WellPanelDepthSampleDto } from "./WellPanelDepthSampleDto";
export type { WellPanelDrillingObservationDto } from "./WellPanelDrillingObservationDto";
export type { WellPanelDrillingSetDto } from "./WellPanelDrillingSetDto";
export type { WellPanelLogCurveDto } from "./WellPanelLogCurveDto";
export type { WellPanelPressureObservationDto } from "./WellPanelPressureObservationDto";
export type { WellPanelPressureSetDto } from "./WellPanelPressureSetDto";
export type { WellPanelRequestDto } from "./WellPanelRequestDto";
export type { WellPanelTopRowDto } from "./WellPanelTopRowDto";
export type { WellPanelTopSetDto } from "./WellPanelTopSetDto";
export type { WellPanelTrajectoryDto } from "./WellPanelTrajectoryDto";
export type { WellPanelTrajectoryRowDto } from "./WellPanelTrajectoryRowDto";
export { WELL_PANEL_CONTRACT_VERSION } from "./well-panel-contract-version";
"#;

    fs::write(output_dir.join("index.ts"), index)?;
    Ok(())
}

fn write_schema_bundle(output_dir: &Path) -> Result<(), Box<dyn Error>> {
    let bundle = serde_json::json!({
        "wellPanelContractVersion": WELL_PANEL_CONTRACT_VERSION,
        "types": {
            "WellPanelRequestDto": schema_for!(WellPanelRequestDto),
            "WellPanelDepthSampleDto": schema_for!(WellPanelDepthSampleDto),
            "WellPanelLogCurveDto": schema_for!(WellPanelLogCurveDto),
            "WellPanelTrajectoryRowDto": schema_for!(WellPanelTrajectoryRowDto),
            "WellPanelTrajectoryDto": schema_for!(WellPanelTrajectoryDto),
            "WellPanelTopRowDto": schema_for!(WellPanelTopRowDto),
            "WellPanelTopSetDto": schema_for!(WellPanelTopSetDto),
            "WellPanelPressureObservationDto": schema_for!(WellPanelPressureObservationDto),
            "WellPanelPressureSetDto": schema_for!(WellPanelPressureSetDto),
            "WellPanelDrillingObservationDto": schema_for!(WellPanelDrillingObservationDto),
            "WellPanelDrillingSetDto": schema_for!(WellPanelDrillingSetDto),
            "ResolvedWellPanelWellDto": schema_for!(ResolvedWellPanelWellDto),
            "ResolvedWellPanelSourceDto": schema_for!(ResolvedWellPanelSourceDto),
            "GatherAxisKind": schema_for!(GatherAxisKind),
            "GatherSampleDomain": schema_for!(GatherSampleDomain),
            "GatherView": schema_for!(GatherView),
            "GatherViewport": schema_for!(GatherViewport),
            "GatherProbe": schema_for!(GatherProbe),
            "GatherViewportChanged": schema_for!(GatherViewportChanged),
            "GatherProbeChanged": schema_for!(GatherProbeChanged),
            "GatherInteractionChanged": schema_for!(GatherInteractionChanged),
        }
    });

    fs::write(
        output_dir.join("ophiolite-contracts.schema.json"),
        serde_json::to_string_pretty(&bundle)?,
    )?;

    Ok(())
}
