use crate::{Endianness, SampleFormat};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FixtureCase {
    pub path: &'static str,
    pub endianness: Endianness,
    pub sample_format: SampleFormat,
    pub samples_per_trace: u16,
    pub trace_count: u64,
    pub extended_textual_headers: i16,
}

const CURATED_FIXTURES: &[FixtureCase] = &[
    FixtureCase {
        path: "small.sgy",
        endianness: Endianness::Big,
        sample_format: SampleFormat::IbmFloat32,
        samples_per_trace: 50,
        trace_count: 25,
        extended_textual_headers: 0,
    },
    FixtureCase {
        path: "small-lsb.sgy",
        endianness: Endianness::Little,
        sample_format: SampleFormat::IbmFloat32,
        samples_per_trace: 50,
        trace_count: 25,
        extended_textual_headers: 0,
    },
    FixtureCase {
        path: "f3.sgy",
        endianness: Endianness::Big,
        sample_format: SampleFormat::Int16,
        samples_per_trace: 75,
        trace_count: 414,
        extended_textual_headers: 0,
    },
    FixtureCase {
        path: "f3-lsb.sgy",
        endianness: Endianness::Little,
        sample_format: SampleFormat::Int16,
        samples_per_trace: 75,
        trace_count: 414,
        extended_textual_headers: 0,
    },
    FixtureCase {
        path: "small-ps.sgy",
        endianness: Endianness::Big,
        sample_format: SampleFormat::IbmFloat32,
        samples_per_trace: 10,
        trace_count: 24,
        extended_textual_headers: 0,
    },
    FixtureCase {
        path: "shot-gather.sgy",
        endianness: Endianness::Big,
        sample_format: SampleFormat::IbmFloat32,
        samples_per_trace: 25,
        trace_count: 61,
        extended_textual_headers: 0,
    },
    FixtureCase {
        path: "multi-text.sgy",
        endianness: Endianness::Big,
        sample_format: SampleFormat::IbmFloat32,
        samples_per_trace: 1,
        trace_count: 1,
        extended_textual_headers: 4,
    },
    FixtureCase {
        path: "text-embed-null.sgy",
        endianness: Endianness::Big,
        sample_format: SampleFormat::IbmFloat32,
        samples_per_trace: 50,
        trace_count: 25,
        extended_textual_headers: 0,
    },
    FixtureCase {
        path: "long.sgy",
        endianness: Endianness::Big,
        sample_format: SampleFormat::IbmFloat32,
        samples_per_trace: 60_000,
        trace_count: 3,
        extended_textual_headers: 0,
    },
    FixtureCase {
        path: "multiformats/Format1msb.sgy",
        endianness: Endianness::Big,
        sample_format: SampleFormat::IbmFloat32,
        samples_per_trace: 75,
        trace_count: 414,
        extended_textual_headers: 0,
    },
    FixtureCase {
        path: "multiformats/Format1lsb.sgy",
        endianness: Endianness::Little,
        sample_format: SampleFormat::IbmFloat32,
        samples_per_trace: 75,
        trace_count: 414,
        extended_textual_headers: 0,
    },
    FixtureCase {
        path: "multiformats/Format3msb.sgy",
        endianness: Endianness::Big,
        sample_format: SampleFormat::Int16,
        samples_per_trace: 75,
        trace_count: 414,
        extended_textual_headers: 0,
    },
    FixtureCase {
        path: "multiformats/Format3lsb.sgy",
        endianness: Endianness::Little,
        sample_format: SampleFormat::Int16,
        samples_per_trace: 75,
        trace_count: 414,
        extended_textual_headers: 0,
    },
    FixtureCase {
        path: "multiformats/Format5msb.sgy",
        endianness: Endianness::Big,
        sample_format: SampleFormat::IeeeFloat32,
        samples_per_trace: 75,
        trace_count: 414,
        extended_textual_headers: 0,
    },
    FixtureCase {
        path: "multiformats/Format5lsb.sgy",
        endianness: Endianness::Little,
        sample_format: SampleFormat::IeeeFloat32,
        samples_per_trace: 75,
        trace_count: 414,
        extended_textual_headers: 0,
    },
    FixtureCase {
        path: "multiformats/Format8msb.sgy",
        endianness: Endianness::Big,
        sample_format: SampleFormat::Int8,
        samples_per_trace: 75,
        trace_count: 414,
        extended_textual_headers: 0,
    },
    FixtureCase {
        path: "multiformats/Format8lsb.sgy",
        endianness: Endianness::Little,
        sample_format: SampleFormat::Int8,
        samples_per_trace: 75,
        trace_count: 414,
        extended_textual_headers: 0,
    },
];

pub fn curated_fixtures() -> &'static [FixtureCase] {
    CURATED_FIXTURES
}
